services:
  server1:
    platform: linux/amd64
    image: server
    build:
      dockerfile: example/Dockerfile
      context: ..
    environment:
      PORT: "3000"
      NEXTHOP: "server2:3000"
    ports:
    - "3000:3000"
  server2:
    platform: linux/amd64
    image: server
    environment:
      PORT: "3000"
      NEXTHOP: "server3:3000"
    ports:
    - "3100:3000"
  server3:
    platform: linux/amd64
    image: server
    environment:
      PORT: "3000"
      NEXTHOP: ""
    ports:
    - "3200:3000"
